name: Manage Merge
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    - cron: 0 * * * *

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: sanjeev-labs/manage-merge@v1.0
        with:
          target_branch: main
          merge_method: merge
          time_zone: "America/Detroit"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
  evt_detail:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT_EVENT_NAME: ${{ toJSON(github.event.event_name) }}
          GITHUB_CONTEXT: ${{ toJSON(github.event.pull_request.body) }}
          GITHUB_CONTEXT_LABEL: ${{ toJSON(github.event.pull_request.labels) }}
          GITHUB_CONTEXT_HAS_LABEL: ${{ contains(github.event.pull_request.labels.*.name, 'deploy-ready') }}
          GITHUB_CONTEXT_HAS: ${{ contains( github.event.pull_request.body, 'deploy-ready') }}
          ALL_CONDITIONS: ${{ (github.base_ref == 'main') && contains( github.event.pull_request.body, 'deploy-ready') }}
        run: |
             echo "$GITHUB_CONTEXT_EVENT_NAME"
             echo "$GITHUB_CONTEXT"
             echo "$GITHUB_CONTEXT_LABEL"
             echo "$GITHUB_CONTEXT_HAS_LABEL"
             echo "$GITHUB_CONTEXT_HAS"
             echo "$ALL_CONDITIONS"


