name: Merge Schedule
on: workflow_dispatch
#  schedule:
#    - cron: 0 8 * * *

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
