name: Merge Schedule
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    - cron: 0 * * * *

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    if: |
        (github.ref == 'refs/heads/main') &&
        contains( github.event.pull_request.body, 'deploy-ready')
    steps:
      - uses: gr2m/merge-schedule-action@v1
        with:
          # Merge method to use. Possible values are merge, squash or
          # rebase. Default is merge.
          merge_method: merge
          #  Time zone to use. Default is UTC.
          time_zone: "America/Detroit"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
  evt_detail:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github.event.pull_request) }}
        run: echo "$GITHUB_CONTEXT"

