name: Merge Schedule
on: workflow_dispatch
#  schedule:
#    - cron: 0 8 * * *

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    if:  github.event.label.name == 'deploy-ready'
    steps:
      - uses: gr2m/merge-schedule-action@v1
        with:
          # Merge method to use. Possible values are merge, squash or
          # rebase. Default is merge.
          merge_method: merge
          #  Time zone to use. Default is UTC.
          time_zone: "Asia/Kolkata"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
